### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by arichiv** [AriChivukula/limbo#53]
- [x]  [seal-rookery](https://github.com/freelawproject/seal-rookery) - https://github.com/freelawproject/seal-rookery/pull/14
- [x] [free.law](https://github.com/freelawproject/free.law) - https://github.com/freelawproject/free.law/pull/31
- [x] [freelawmachine](https://github.com/freelawproject/freelawmachine) - https://github.com/freelawproject/freelawmachine/pull/33
- [ ] [courtlistener](https://github.com/freelawproject/courtlistener)
- [ ] [court-listener-api-definition](https://github.com/freelawproject/court-listener-api-definition)

**Comment by arichiv** [comment]
@kinlane continuing discussion from https://github.com/freelawproject/court-listener-api-definition/issues/4

**Comment by arichiv** [comment]
@mlissner what's the entry point for courtlistener installed without vagrant?

**Comment by mlissner** [comment]
How do you mean, "entry point"?

**Comment by arichiv** [comment]
What do I run? The repo has a lot of folders and the documentation for a non-vagrant build says its out of date @mlissner

**Comment by arichiv** [comment]
I want to build CourtListener on TravisCI without Vagrant. If that isn't possible, I can work on getting Vagrant to work :-)

**Comment by arichiv** [comment]
More specifically, I'm wondering if https://github.com/freelawproject/courtlistener/wiki/Installing-CourtListener-on-Ubuntu-Linux is up to date @mlissner

**Comment by mlissner** [comment]
Oh I see! OK. I don't think that Wiki entry is accurate, no. The best thing to do is to look at the vagrant and Ansible scripts and see what they're doing. They're the same as the Wiki except they should have everything all coded up nicely so that computers can understand it. 

I haven't stood up a fresh new installation in a while, so some things are likely to be a little broken, but I think it should still be pretty straightforward. I do not, however, expect Travis to be able to complete this quickly. I'd bet it would take over an hour of downloads and installations, if not more, to download, compile and install everything.
